# Generated by Django 4.1.3 on 2023-06-30 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('idReserva', models.AutoField(primary_key=True, serialize=False, verbose_name='Id de la reserva')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut del paciente')),
                ('email', models.CharField(max_length=50, verbose_name='Correo del destinatario')),
                ('idPres', models.IntegerField(verbose_name='Id de la prescripcion de los reservados')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado de la reserva')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
            ],
        ),
    ]
